/* Automatically generated by configure - do not modify */
#include "../config-host.h"
#define CONFIG_QEMU_PREFIX "/usr/gnemul/qemu-mips64el"
#define TARGET_ARCH "mips64"
#define TARGET_MIPS 1
#define TARGET_MIPS64 1
#define TARGET_ABI_MIPSN64 1
#define CONFIG_SOFTMMU 1
#define CONFIG_SOFTFLOAT 1
