/* Automatically generated by configure - do not modify */
#include "../config-host.h"
#define CONFIG_QEMU_PREFIX "/usr/gnemul/qemu-arm"
#define TARGET_ARCH "arm"
#define TARGET_ARM 1
#define CONFIG_SOFTMMU 1
#define CONFIG_SOFTFLOAT 1
