#!/usr/bin/env python
# -*- coding: utf-8 -*-

## Copyright 2009-2020 NTESS. Under the terms
## of Contract DE-NA0003525 with NTESS, the U.S.
## Government retains certain rights in this software.
##
## Copyright (c) 2009-2019, NTESS
## All rights reserved.
##
## This file is part of the SST software package. For license
## information, see the LICENSE file in the top level directory of the
## distribution.

import sys
import os.path
import traceback

try:
    import ssttestengineloader
except Exception as e:
    print("FATAL: Failed to load ssttestengineloader.py ({0})".format(e))
    quit(1)

#################################################
# Script Entry
#################################################
if __name__ == "__main__":
    try:
        # Get the path of where this file is launched
        SSTCoreBinDir = os.path.dirname(os.path.abspath(__file__))
        # Run the test engine in Elements Mode
        ssttestengineloader.startupAndRun(SSTCoreBinDir, testCoreMode = False)
    except Exception as e:
        print(("FATAL: SST Test Frameworks encountered ") +
              ("an unexpected exception ({0}))".format(e)))
        print("\n=============================================================")
        print("==== TRACEBACK ===============================================")
        print("==============================================================")
        traceback.print_exc(file=sys.stdout)
        print("==============================================================")
        sys.exit(1)

