#!/usr/bin/env python
# -*- coding: utf-8 -*-

## Copyright 2009-2020 NTESS. Under the terms
## of Contract DE-NA0003525 with NTESS, the U.S.
## Government retains certain rights in this software.
##
## Copyright (c) 2009-2019, NTESS
## All rights reserved.
##
## This file is part of the SST software package. For license
## information, see the LICENSE file in the top level directory of the
## distribution.

""" This module is the entry point for testing the SST Registerd Elements
"""

import sys
import os.path
import traceback

try:
    import ssttestengineloader
except ImportError as exc_e:
    print("FATAL: Failed to load ssttestengineloader.py ({0})".format(exc_e))
    sys.exit(1)

#################################################
# Script Entry
#################################################
if __name__ == "__main__":
    try:
        # Get the path of where this file is launched
        SSTCOREBINDIR = os.path.dirname(os.path.abspath(__file__))
        # Run the test engine in Elements Mode
        ssttestengineloader.startup_and_run(SSTCOREBINDIR, test_core_mode=False)
    except Exception as exc_e:
        # NOTE: This is a generic catchall handler for any unhandled exception
        print(("FATAL: SST Test Frameworks encountered ") +
              ("an unexpected exception ({0}))".format(exc_e)))
        print("\n=============================================================")
        print("==== TRACEBACK ===============================================")
        print("==============================================================")
        traceback.print_exc(file=sys.stdout)
        print("==============================================================")
        sys.exit(1)
