# Automatically generated by configure - do not modify
include ../config-host.mak
TARGET_ARCH=sh4
TARGET_WORDS_BIGENDIAN=yes
CONFIG_USER_ONLY=yes
CONFIG_LINUX_USER=yes
TARGET_XML_FILES=
TARGET_HAS_BFLT=yes
