/* Automatically generated by configure - do not modify */
#define CONFIG_QEMU_SHAREDIR "/usr/local/share/qemu"
#define HOST_X86_64 1
#define HOST_LONG_BITS 64
#define HAVE_BYTESWAP_H 1
#define CONFIG_GDBSTUB 1
#define CONFIG_SLIRP 1
#define AUDIO_DRIVERS \

#define CONFIG_VNC_TLS 1
#define QEMU_VERSION "0.10.5"
#define HAVE_IOVEC 1
#define CONFIG_UNAME_RELEASE ""
