/* Automatically generated by configure - do not modify */
#include "../config-host.h"
#define CONFIG_QEMU_PREFIX "/usr/gnemul/qemu-mipsel"
#define TARGET_ARCH "mips"
#define TARGET_MIPS 1
#define TARGET_ABI_MIPSO32 1
#define CONFIG_USER_ONLY 1
#define CONFIG_LINUX_USER 1
#define CONFIG_SOFTFLOAT 1
