#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os.path

try:
    import ssttestloader
except Exception as e:
    print("FATAL: Failed to load ssttestloader.py ({0})".format(e))
    quit(1)

#################################################
# Script Entry
#################################################
if __name__ == "__main__":
    try:
        SSTCoreBinDir = os.path.dirname(os.path.abspath(__file__))
        # Run the test engine in Elements Mode
        ssttestloader.testEntry(SSTCoreBinDir, testCoreMode = False)
    except Exception as e:
        print(("FATAL: SST Test Frameworks encountered ") +
              ("an unexpected exception ({0}))".format(e)))
        quit(1)

