#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import os.path

#################################################

TESTFRAMEWORKSFILES = ["test_globals.py", "test_support.py", "test_engine.py"]
TEST_CORE_MODE      = True  # True = Test SST-Core

#################################################

def main():
    # Get the Current directory (this should be the SST-Core/bin dir)
    # and set the path of the testframeworks dir
    SSTCoreBinDir = os.path.dirname(__file__)
    SSTCoreTestFrameworksDir = SSTCoreBinDir + "/testframeworks/"

    verifyTestFrameworkIsAvailable(SSTCoreTestFrameworksDir)

    # Now try to import the test framework components
    sys.path.insert(1, SSTCoreTestFrameworksDir)
    import test_engine

    # Create the Test Engine and run it
    te = test_engine.TestEngine(TEST_CORE_MODE,
                                SSTCoreBinDir,
                                SSTCoreTestFrameworksDir)
    te.runTests()

###

def verifyTestFrameworkIsAvailable(SSTCoreFrameworksDir):
    # Verify that the frameworks files exist in testframeworks subdirectory
    frameworksFound = True
    for filename in TESTFRAMEWORKSFILES:
        filesearchpath =  SSTCoreFrameworksDir + filename
        if not os.path.isfile(filesearchpath):
            print (("WARNING: Missing test framework file " +
                    "{0}".format(filesearchpath)))
            frameworksFound = False

    if not frameworksFound:
        print (("ERROR: Testing cannot be performed due to missing ") +
               ("frameworks files...\n"))
        sys.exit(1)

    return SSTCoreFrameworksDir

#################################################
#################################################
#################################################
#################################################
#################################################
#################################################
#################################################
#################################################
#################################################
#################################################
#################################################
#################################################
#################################################


#    # Startup checks to make sure everything is in order
#    startup = StartupChecks()
#
#    # Now try to import the test framework
#    sys.path.insert(1, startup._SSTCoreFrameworksDir)
#    import test_engine
#
#    # Create the Test Engine and run it
#    te = test_engine.TestEngine(TESTMODE_CORE,
#                                startup._parser,
#                                startup._SSTCoreBinDir,
#                                startup._SSTCoreSSTAppPath,
#                                startup._sstStartupTopDir)
#    te.runTests()
#
##################################################
#
#class StartupChecks():
#    def __init__(self):
#        # Init some variables
#        self._parser = None
#        self._userDefinedCoreDir = None
#        self._SSTCoreBinDir = None
#        self._SSTCoreSSTAppPath = None
#        self._SSTCoreFrameworksDir = None
#        self._sstStartupTopDir = os.path.dirname(__file__)
#
#        print ("AARON - STARTUP DIR = {0}".format(self._sstStartupTopDir))
#
#        # Perform checks and handle the arguments,
#        self.validatePythonVersion()
#        self.parseArguments()
#        self.verifyCoreIsInstalled()
#        self.verifyTestFrameworkIsAvailable()
#
####
#
#    def validatePythonVersion(self):
#        ver = sys.version_info
#        if (ver[0] < REQUIRED_PY_MAJ_VER_2) and (ver[0] < REQUIRED_PY_MAJ_VER_MAX):
#            print(("FATAL:\n{0} requires Python major version {1} or {2}\n" +
#                   "Found Python version is:\n{3}").format(os.path.basename(__file__),
#                                                           REQUIRED_PY_MAJ_VER_2,
#                                                           REQUIRED_PY_MAJ_VER_MAX,
#                                                           sys.version))
#            sys.exit(1)
#
#        if (ver[0] == REQUIRED_PY_MAJ_VER_2) and (ver[1] < REQUIRED_PY_MAJ_VER_2_MINOR_VER):
#            print(("FATAL:\n{0} requires Python version {1}.{2} or greater\n" +
#                   "Found Python version is:\n{3}").format(os.path.basename(__file__),
#                                                           REQUIRED_PY_MAJ_VER_2,
#                                                           REQUIRED_PY_MAJ_VER_2_MINOR_VER,
#                                                           sys.version))
#
#            sys.exit(1)
#
####
#
#    def parseArguments(self):
#        # We are building a preliminary parser to help identify where
#        # the SST-Core exists.  It can be in the $PATH or identifed by
#        # the user.  Once the pre-parse the arguments, we will pass this
#        # Parser to the test engine for a more explicit check of arguments.
#        parser = argparse.ArgumentParser(description=HELP_DESC,
#                                         epilog=HELP_EPILOG,
#                                         add_help = False)
#
#        parser.add_argument('-c', '--sst-core-dir', type=str, metavar='dir',
#                            nargs='?', default='',
#                            help = 'Installed Core Directory')
#
#        # NOTE: We pre-parse the existing args, but have disabled the Help
#        # feature.  If we cannot find SST then we will the print the existing
#        # argparse help feature.  Otherwise, we let the parser code in the
#        # test_engine add more args and handle the -h option
#        args = parser.parse_known_args()
#
#        if args[0].sst_core_dir == None:
#            args[0].sst_core_dir = "UNDEFINED_DIR"
#
#        # Extract the Arguments into the class variables
#        self._userDefinedCoreDir = args[0].sst_core_dir
#        self._parser = parser
#
####
#
#    def verifyCoreIsInstalled(self):
#        # See if we can find the binary version of sst-core in the user
#        # defined path or in the $PATH env var
#
#        foundSSTCoreBinPath = ""
#        # Did the user define a path to the SST-Core?
#        if self._userDefinedCoreDir != '':
#            coreBinDir = self._userDefinedCoreDir + "/bin"
#            foundSSTAppPath = coreBinDir + "/sst"
#            if not os.path.isdir(self._userDefinedCoreDir):
#                print (("\nERROR: Unable to find SST Core directory defined " +
#                        "by user at {0}\n".format(self._userDefinedCoreDir)))
#            elif not os.path.isfile(foundSSTAppPath):
#                print (("\nERROR: Unable to find SST application at user " +
#                        "defined path {0}\n".format(foundSSTAppPath)))
#            else:
#                foundSSTCoreBinPath = coreBinDir
#        else:
#            # Try to find the SST Core Bin dir in the $PATH
#            try:
#                searchCmd = ["which", "sst"]
#                foundSSTAppPath = subprocess.check_output(searchCmd)
#                foundSSTCoreBinPath = os.path.dirname(foundSSTAppPath)
#            except subprocess.CalledProcessError as e:
#                pass
#            except OSError as e:
#                print ("Got an OSError on cmd - {0} : {1}".format(searchCmd, e))
#            except Exception as e:
#                print ("Got an Exception on cmd - {0} : {1}".format(searchCmd, e))
#
#            if foundSSTCoreBinPath == "":
#                print (("\nERROR: Unable to find SST application in Core bin ") +
#                       ("directory by searching $PATH\n"))
#
#        # Now see if we really did find a core.
#        if foundSSTCoreBinPath == "":
#            self.parser.print_help()
#            sys.exit(1)
#        else:
#            self._SSTCoreBinDir = foundSSTCoreBinPath
#            self._SSTCoreSSTAppPath = foundSSTAppPath
#            print ("NOTICE: SSTCore bin Dir is Found at {0}".format(self._SSTCoreBinDir))
#            print ("NOTICE: SST Application is Found at {0}".format(self._SSTCoreSSTAppPath.strip("\n")))
#
####
#
#    def verifyTestFrameworkIsAvailable(self):
#        # Verify that the frameworks files exist in the installed core dir
#        frameworksFound = True
#        for filename in TESTFRAMEWORKSFILES:
#            self._SSTCoreFrameworksDir = self._SSTCoreBinDir + "/testframeworks/"
#            filesearchpath =  self._SSTCoreFrameworksDir + filename
#            if not os.path.isfile(filesearchpath):
#                print (("WARNING: Missing test framework file " +
#                        "{0}".format(filesearchpath)))
#                frameworksFound = False
#
#        if not frameworksFound:
#            print ("ERROR: Testing cannot be performed due to missing frameworks files...\n")
#            sys.exit(1)
#
####
#
#    def verifyElementsIsInstalled(self):
#        # TODO: We may not need this
#        # See if we can determine if elements have been installed
#        pass

#################################################
# Script Entry
#################################################
if __name__ == "__main__":
    # Call the main() subroutine
    main()

