# -*- Makefile -*-
#
#

sst_core_sources += \
	sync/rankSyncParallelSkip.h \
	sync/rankSyncParallelSkip.cc \
	sync/rankSyncSerialSkip.h \
	sync/rankSyncSerialSkip.cc \
	sync/syncManager.h \
	sync/syncManager.cc \
	sync/syncQueue.h \
	sync/syncQueue.cc \
	sync/threadSyncSimpleSkip.h \
	sync/threadSyncSimpleSkip.cc \
	sync/threadSyncQueue.h
