# Automatically generated by configure - do not modify
include ../config-host.mak
TARGET_ARCH=ppc64
TARGET_ABI_DIR=ppc
TARGET_WORDS_BIGENDIAN=yes
CONFIG_SOFTMMU=yes
TARGET_XML_FILES= /home/cdkerse/hack/multirun/ports/qemu/gdb-xml/power64-core.xml /home/cdkerse/hack/multirun/ports/qemu/gdb-xml/power-fpu.xml /home/cdkerse/hack/multirun/ports/qemu/gdb-xml/power-altivec.xml /home/cdkerse/hack/multirun/ports/qemu/gdb-xml/power-spe.xml
CONFIG_SOFTFLOAT=yes
