/* Automatically generated by configure - do not modify */
#include "../config-host.h"
#define CONFIG_QEMU_PREFIX "/usr/gnemul/qemu-ppcemb"
#define TARGET_ARCH "ppcemb"
#define TARGET_PPC 1
#define TARGET_PPCEMB 1
#define TARGET_WORDS_BIGENDIAN 1
#define CONFIG_SOFTMMU 1
#define CONFIG_SOFTFLOAT 1
