/* Automatically generated by configure - do not modify */
#include "../config-host.h"
#define CONFIG_QEMU_PREFIX "/usr/gnemul/qemu-alpha"
#define TARGET_ARCH "alpha"
#define TARGET_ALPHA 1
#define CONFIG_USER_ONLY 1
#define CONFIG_LINUX_USER 1
