# Automatically generated by configure - do not modify
include ../config-host.mak
TARGET_ARCH=sparc64
TARGET_ABI_DIR=sparc
TARGET_ARCH2=sparc32plus
TARGET_WORDS_BIGENDIAN=yes
CONFIG_USER_ONLY=yes
CONFIG_LINUX_USER=yes
TARGET_XML_FILES=
CONFIG_SOFTFLOAT=yes
