/* Automatically generated by configure - do not modify */
#include "../config-host.h"
#define CONFIG_QEMU_PREFIX "/usr/gnemul/qemu-m68k"
#define TARGET_ARCH "m68k"
#define TARGET_M68K 1
#define TARGET_WORDS_BIGENDIAN 1
#define CONFIG_USER_ONLY 1
#define CONFIG_LINUX_USER 1
#define CONFIG_SOFTFLOAT 1
#define TARGET_HAS_BFLT 1
