/* Automatically generated by configure - do not modify */
#include "../config-host.h"
#define CONFIG_QEMU_PREFIX "/usr/gnemul/qemu-cris"
#define TARGET_ARCH "cris"
#define TARGET_CRIS 1
#define CONFIG_USER_ONLY 1
#define CONFIG_LINUX_USER 1
