/* Automatically generated by configure - do not modify */
#include "../config-host.h"
#define CONFIG_QEMU_PREFIX "/usr/gnemul/qemu-sparc"
#define TARGET_ARCH "sparc"
#define TARGET_SPARC 1
#define TARGET_WORDS_BIGENDIAN 1
#define CONFIG_USER_ONLY 1
#define CONFIG_LINUX_USER 1
#define CONFIG_SOFTFLOAT 1
