
# -*- Makefile -*-
#
#

sst_core_sources += \
	impl/interactive/debugConsole.cc \
	impl/interactive/debugConsole.h \
	impl/interactive/cmdLineEditor.cc \
	impl/interactive/cmdLineEditor.h \
	impl/interactive/debugStream.h  \
	impl/interactive/debugStream.cc