/* Automatically generated by configure - do not modify */
#include "../config-host.h"
#define CONFIG_QEMU_PREFIX "/usr/gnemul/qemu-x86_64"
#define TARGET_ARCH "x86_64"
#define TARGET_I386 1
#define TARGET_X86_64 1
#define CONFIG_USER_ONLY 1
#define CONFIG_LINUX_USER 1
