/* Automatically generated by configure - do not modify */
#include "../config-host.h"
#define CONFIG_QEMU_PREFIX "/usr/gnemul/qemu-sh4"
#define TARGET_ARCH "sh4"
#define TARGET_SH4 1
#define CONFIG_USER_ONLY 1
#define CONFIG_LINUX_USER 1
#define TARGET_HAS_BFLT 1
