name: SST-CORE clang-format TEST

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - master
      - devel

defaults:
  run:
    shell: bash -l {0}

jobs:
  Test_With_clang-format:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
#        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9]
        python-version: [3.8]
    name: Test:${{ matrix.os }}/PY-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    steps:
#   Checkout this users SST-core repo/branch
    - name: Checkout Users SST-Core source
      uses: actions/checkout@v2
      with:
        path: ./sst-core_source

#   Running the github action for clang format
    - name: Run Action clang-format-lint
      uses: DoozyX/clang-format-lint-action@v0.12
      with:
        source: './sst-core_source/'
        exclude: './sst-core_source/src/sst/core/libltdl ./sst-core_source/external ./sst-core_source/build'
        extensions: 'h,cc'
        clangFormatVersion: 12
        inplace: False

# Label the Results
    - name: Label Results
      if: ${{ failure() }}
      run: |
        echo "LABEL FAILURE"
      if: ${{ success() }}
      run: |
        echo "LABEL SUCCESS"
#      uses: actions/heroku@1.0.0
