name: SST-CORE clang-format TEST

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - master
      - devel

defaults:
  run:
    shell: bash -l {0}

jobs:
  Build_and_Test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
#        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9]
        python-version: [3.8]
    name: Test:${{ matrix.os }}/PY-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: System Information Dump - Startup
      run: |
        echo "*******************************************"
        echo "*** SYSTEM INFO DUMP AT STARTUP"
        echo "*******************************************"
        echo
        echo "pwd = " `pwd`
        echo "***"
        echo "env | sort = "
        env | sort
        echo "***"
    - name: Set Source and General Install Env Variables
      run: |
        echo "*******************************************"
        echo "*** SET SOURCE AND LOCAL DIR ENV VAR (THIS AFFECTS FUTURE STEPS)"
        echo "*******************************************"
        echo "SST_SOURCE_PATH=$HOME/work/sst-core/sst-core" >> $GITHUB_ENV
        echo "SST_GEN_INSTALL_PATH=$HOME/local" >> $GITHUB_ENV
        echo "***"
        echo "LOCATION OF GITHUB_ENV SCRIPT"
        echo $GITHUB_ENV
        echo "***"
        echo "CONTENTS OF GITHUB_ENV"
        cat $GITHUB_ENV
        echo "***"
    - name: Set SST Core Install Env Variables
      run: |
        echo "*******************************************"
        echo "*** SET ENV VARS (THIS AFFECTS FUTURE STEPS)"
        echo "*******************************************"
        echo "SST_CORE_SOURCE_PATH=$SST_SOURCE_PATH/sst-core_source" >> $GITHUB_ENV
        echo "SST_CORE_HOME=$SST_GEN_INSTALL_PATH/sstcore_install" >> $GITHUB_ENV
        echo "SST_CORE_BIN=$SST_GEN_INSTALL_PATH/sstcore_install/bin" >> $GITHUB_ENV
        echo "***"
        echo "LOCATION OF GITHUB_ENV SCRIPT"
        echo $GITHUB_ENV
        echo "***"
        echo "CONTENTS OF GITHUB_ENV"
        cat $GITHUB_ENV
        echo "***"

#   Checkout this users SST-core repo/branch
    - name: Checkout Users SST-Core source
      uses: actions/checkout@v2
      with:
        path: ./sst-core_source

    - name: System Information Dump - Before Build
      run: |
        echo "*******************************************"
        echo "*** SYSTEM INFO DUMP BEFORE RUN"
        echo "*******************************************"
        echo
        echo "pwd = " `pwd`
        echo "***"
        echo "env | sort = "
        env | sort
        echo "***"

    - name: Run the clang-format script
      run: |
        echo "*******************************************"
        echo "*** CHANGE DIRECTORY TO SST-Core SOURCE DIR"
        echo "*******************************************"
        cd $SST_CORE_SOURCE_PATH

        echo "CLANG FORMAT VERSION"
        clang-format --version

        ./scripts/clang-format-test.sh
        rtn_code=$?
        echo "*** clang-format-test.sh returned =" $rtn_code

#   Try running the github action for clang format
    - name: Rut clang-format-lint-action
      uses: DoozyX/clang-format-lint-action@v0.12
      with:
        source: '$SST_CORE_SOURCE_PATH'
        exclude: '$SST_CORE_SOURCE_PATH//src/sst/core/libltdl $SST_CORE_SOURCE_PATH/external'
        extensions: 'h,cc'
        clangFormatVersion: 12
        inplace: False

